version: '3.7'
services:
  postgre:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gacha